# 6.1 Data clean and Data Consistency Checks


## -Find and address mixed type variables in a dataframe¶
## -Find and address missing values in a dataframe
## -Find and address duplicate values in a dataframe

In [1]:
# import libraries
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [2]:
# open data adidas
path = Path("C:/", "Users", "nayla", "Desktop", "Carrer F", "Curso de inmersion", "Unidad 6")


In [3]:
data = pd.read_csv(
    path.joinpath('02 data', 'Adidas_US_Sales.csv'), 
    index_col = False, 
    skiprows=4, 
    sep=";",
    thousands='.', # when I open the file with a text editor I see 300.000$ which is not 300$ but 300000$
    decimal=',' # As well I see 1,234$ which is 1.234$
)


In [4]:
#Control data
data.shape

(9648, 13)

In [5]:
data.dtypes

Retailer            object
Retailer ID          int64
Invoice Date        object
Region              object
State               object
City                object
Product             object
Price per Unit      object
Units Sold           int64
Total Sales         object
Operating Profit    object
Operating Margin    object
Sales Method        object
dtype: object

## Missing values

In [6]:
# show missing values
data.isnull().sum()

Retailer            0
Retailer ID         0
Invoice Date        0
Region              0
State               0
City                0
Product             0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Operating Margin    0
Sales Method        0
dtype: int64

Table columns do not contain null values

## Duplicates

In [7]:
#look for full duplicates within your dataframe:
data_dups = data[data.duplicated()]

In [8]:
data_dups

Empty DataFrame
Columns: [Retailer, Retailer ID, Invoice Date, Region, State, City, Product, Price per Unit, Units Sold, Total Sales, Operating Profit, Operating Margin, Sales Method]
Index: []

Table columns do not contain duplicates

## Fix data types

In [9]:
data.dtypes

Retailer            object
Retailer ID          int64
Invoice Date        object
Region              object
State               object
City                object
Product             object
Price per Unit      object
Units Sold           int64
Total Sales         object
Operating Profit    object
Operating Margin    object
Sales Method        object
dtype: object

## Consistency checks

### - Retail ID

In [10]:
# Retailer should be a string
data['Retailer'] = data['Retailer'].astype('str')
# Verify we have consistent values
data['Retailer'].unique()

array(['Foot Locker', 'Walmart', 'Sports Direct', 'West Gear', "Kohl's",
       'Amazon'], dtype=object)

In [11]:
# Retailer ID was identified as a number properly
# verify we have consistent values, and the amounts match the amounts from Retailer
data['Retailer ID'].unique()

array([1185732, 1197831, 1128299, 1189833], dtype=int64)

In [12]:
# Sizes don't match, so we need to investigate
np.unique(data.apply(lambda x: (x['Retailer ID'], x['Retailer']), axis=1, result_type='reduce').values)


array([(1128299, 'Foot Locker'), (1128299, "Kohl's"),
       (1128299, 'Sports Direct'), (1128299, 'Walmart'),
       (1128299, 'West Gear'), (1185732, 'Amazon'),
       (1185732, 'Foot Locker'), (1185732, "Kohl's"),
       (1185732, 'Sports Direct'), (1185732, 'Walmart'),
       (1185732, 'West Gear'), (1189833, "Kohl's"),
       (1197831, 'Foot Locker'), (1197831, "Kohl's"),
       (1197831, 'Sports Direct'), (1197831, 'Walmart'),
       (1197831, 'West Gear')], dtype=object)

In [13]:
#delete column Retail ID
data.drop(['Retailer ID'], axis=1, inplace=True)
data

Retailer Invoice Date     Region          State        City  \
0     Foot Locker   01/01/2020  Northeast       New York    New York   
1     Foot Locker   02/01/2020  Northeast       New York    New York   
2     Foot Locker   03/01/2020  Northeast       New York    New York   
3     Foot Locker   04/01/2020  Northeast       New York    New York   
4     Foot Locker   05/01/2020  Northeast       New York    New York   
...           ...          ...        ...            ...         ...   
9643  Foot Locker   24/01/2021  Northeast  New Hampshire  Manchester   
9644  Foot Locker   24/01/2021  Northeast  New Hampshire  Manchester   
9645  Foot Locker   22/02/2021  Northeast  New Hampshire  Manchester   
9646  Foot Locker   22/02/2021  Northeast  New Hampshire  Manchester   
9647  Foot Locker   22/02/2021  Northeast  New Hampshire  Manchester   

                        Product Price per Unit  Units Sold Total Sales  \
0         Men's Street Footwear        $50,00         1200   $600.000    
1       Men's Athletic Footwear        $50,00         1000   $500.000    
2       Women's Street Footwear        $40,00         1000   $400.000    
3     Women's Athletic Footwear        $45,00          850   $382.500    
4                 Men's Apparel        $60,00          900   $540.000    
...                         ...            ...         ...         ...   
9643              Men's Apparel        $50,00           64     $3.200    
9644            Women's Apparel        $41,00          105     $4.305    
9645      Men's Street Footwear        $41,00          184     $7.544    
9646    Men's Athletic Footwear        $42,00           70     $2.940    
9647    Women's Street Footwear        $29,00           83     $2.407    

     Operating Profit Operating Margin Sales Method  
0           $300.000               50%     In-store  
1           $150.000               30%     In-store  
2           $140.000               35%     In-store  
3           $133.875               35%     In-store  
4           $162.000               30%     In-store  
...               ...              ...          ...  
9643            $896               28%       Outlet  
9644          $1.378               32%       Outlet  
9645          $2.791               37%       Outlet  
9646          $1.235               42%       Outlet  
9647            $650               27%       Outlet  

[9648 rows x 12 columns]

Retailer ID makes no sense, same ID used for multiple Retailers so we're dropping that column


### - Invoice date

In [14]:
data['Invoice Date'].unique()

array(['01/01/2020', '02/01/2020', '03/01/2020', '04/01/2020',
       '05/01/2020', '06/01/2020', '07/01/2020', '08/01/2020',
       '21/01/2020', '22/01/2020', '23/01/2020', '24/01/2020',
       '25/01/2020', '26/01/2020', '27/01/2020', '28/01/2020',
       '29/01/2020', '30/01/2020', '31/01/2020', '01/02/2020',
       '02/02/2020', '03/02/2020', '04/02/2020', '05/02/2020',
       '06/02/2020', '07/02/2020', '08/02/2020', '09/02/2020',
       '10/02/2020', '03/03/2020', '04/03/2020', '05/03/2020',
       '06/03/2020', '07/03/2020', '08/03/2020', '09/03/2020',
       '10/03/2020', '11/03/2020', '12/03/2020', '13/03/2020',
       '14/03/2020', '15/03/2020', '16/03/2020', '17/03/2020',
       '18/03/2020', '31/03/2020', '17/04/2020', '18/04/2020',
       '19/04/2020', '20/04/2020', '21/04/2020', '22/04/2020',
       '23/04/2020', '24/04/2020', '25/04/2020', '26/04/2020',
       '27/04/2020', '28/04/2020', '29/04/2020', '30/04/2020',
       '01/05/2020', '02/05/2020', '03/05/2020', '04/05

In [15]:
# dates are normalized, but we need to convert them to a datetime so sorting works fine
data['Invoice Date'] = pd.to_datetime(data['Invoice Date']).dt.date
data['Invoice Date'].unique()


array([datetime.date(2020, 1, 1), datetime.date(2020, 2, 1),
       datetime.date(2020, 3, 1), datetime.date(2020, 4, 1),
       datetime.date(2020, 5, 1), datetime.date(2020, 6, 1),
       datetime.date(2020, 7, 1), datetime.date(2020, 8, 1),
       datetime.date(2020, 1, 21), datetime.date(2020, 1, 22),
       datetime.date(2020, 1, 23), datetime.date(2020, 1, 24),
       datetime.date(2020, 1, 25), datetime.date(2020, 1, 26),
       datetime.date(2020, 1, 27), datetime.date(2020, 1, 28),
       datetime.date(2020, 1, 29), datetime.date(2020, 1, 30),
       datetime.date(2020, 1, 31), datetime.date(2020, 1, 2),
       datetime.date(2020, 2, 2), datetime.date(2020, 3, 2),
       datetime.date(2020, 4, 2), datetime.date(2020, 5, 2),
       datetime.date(2020, 6, 2), datetime.date(2020, 7, 2),
       datetime.date(2020, 8, 2), datetime.date(2020, 9, 2),
       datetime.date(2020, 10, 2), datetime.date(2020, 3, 3),
       datetime.date(2020, 4, 3), datetime.date(2020, 5, 3),
       datet

### - Region, State, City

In [16]:
data['Region'].unique()

array(['Northeast', 'South', 'West', 'Midwest', 'Southeast'], dtype=object)

In [17]:
data['State'].unique()

array(['New York', 'Texas', 'California', 'Illinois', 'Pennsylvania',
       'Nevada', 'Colorado', 'Washington', 'Florida', 'Minnesota',
       'Montana', 'Tennessee', 'Nebraska', 'Alabama', 'Maine', 'Alaska',
       'Hawaii', 'Wyoming', 'Virginia', 'Michigan', 'Missouri', 'Utah',
       'Oregon', 'Louisiana', 'Idaho', 'Arizona', 'New Mexico', 'Georgia',
       'South Carolina', 'North Carolina', 'Ohio', 'Kentucky',
       'Mississippi', 'Arkansas', 'Oklahoma', 'Kansas', 'South Dakota',
       'North Dakota', 'Iowa', 'Wisconsin', 'Indiana', 'West Virginia',
       'Maryland', 'Delaware', 'New Jersey', 'Connecticut',
       'Rhode Island', 'Massachusetts', 'Vermont', 'New Hampshire'],
      dtype=object)

In [18]:
data['City'].unique()

array(['New York', 'Houston', 'San Francisco', 'Los Angeles', 'Chicago',
       'Dallas', 'Philadelphia', 'Las Vegas', 'Denver', 'Seattle',
       'Miami', 'Minneapolis', 'Billings', 'Knoxville', 'Omaha',
       'Birmingham', 'Portland', 'Anchorage', 'Honolulu', 'Orlando',
       'Albany', 'Cheyenne', 'Richmond', 'Detroit', 'St. Louis',
       'Salt Lake City', 'New Orleans', 'Boise', 'Phoenix', 'Albuquerque',
       'Atlanta', 'Charleston', 'Charlotte', 'Columbus', 'Louisville',
       'Jackson', 'Little Rock', 'Oklahoma City', 'Wichita',
       'Sioux Falls', 'Fargo', 'Des Moines', 'Milwaukee', 'Indianapolis',
       'Baltimore', 'Wilmington', 'Newark', 'Hartford', 'Providence',
       'Boston', 'Burlington', 'Manchester'], dtype=object)

### -Product

In [19]:
data['Product'].unique()

array(["Men's Street Footwear", "Men's Athletic Footwear",
       "Women's Street Footwear", "Women's Athletic Footwear",
       "Men's Apparel", "Women's Apparel"], dtype=object)

### Price per Unit, Units Sold, Total Sales, Operating Profit, Operating Margin

In [20]:
def convert_series_from_dollar_to_number(values, _type='float64'):
    '''
    Given a series of values that could look like '$1.213,123' maps it to 1213.123
    
    If a value is using comas instead of dots as decimal separator it fixes the input
    '''
    values = values.map(lambda x: x.strip().replace('.','').replace(',', '.'))
    verify = False not in values.map(lambda x: x.startswith('$')).unique()
    if not verify:
        raise Exception("not all values start with $")
    # convert first to float64 because there could be decimals then the requested type
    return values.map(lambda x: x[1:]).astype('float64').astype(_type)

In [21]:
data['Price per Unit'].unique()

array(['$50,00 ', '$40,00 ', '$45,00 ', '$60,00 ', '$55,00 ', '$65,00 ',
       '$70,00 ', '$25,00 ', '$35,00 ', '$30,00 ', '$80,00 ', '$75,00 ',
       '$20,00 ', '$85,00 ', '$100,00 ', '$90,00 ', '$95,00 ', '$15,00 ',
       '$10,00 ', '$110,00 ', '$105,00 ', '$47,00 ', '$36,00 ', '$41,00 ',
       '$46,00 ', '$44,00 ', '$58,00 ', '$48,00 ', '$39,00 ', '$43,00 ',
       '$59,00 ', '$56,00 ', '$49,00 ', '$54,00 ', '$64,00 ', '$53,00 ',
       '$61,00 ', '$62,00 ', '$68,00 ', '$52,00 ', '$66,00 ', '$51,00 ',
       '$24,00 ', '$34,00 ', '$33,00 ', '$23,00 ', '$32,00 ', '$38,00 ',
       '$29,00 ', '$37,00 ', '$27,00 ', '$42,00 ', '$72,00 ', '$63,00 ',
       '$69,00 ', '$76,00 ', '$67,00 ', '$57,00 ', '$28,00 ', '$18,00 ',
       '$19,00 ', '$71,00 ', '$78,00 ', '$73,00 ', '$74,00 ', '$83,00 ',
       '$82,00 ', '$98,00 ', '$77,00 ', '$88,00 ', '$86,00 ', '$14,00 ',
       '$9,00 ', '$97,00 ', '$81,00 ', '$79,00 ', '$96,00 ', '$84,00 ',
       '$89,00 ', '$103,00 ', '$101,00 ', '$87,00

In [22]:
data['Price per Unit'] = convert_series_from_dollar_to_number(data['Price per Unit'], 'int64')

In [23]:
data['Price per Unit'].unique()

array([ 50,  40,  45,  60,  55,  65,  70,  25,  35,  30,  80,  75,  20,
        85, 100,  90,  95,  15,  10, 110, 105,  47,  36,  41,  46,  44,
        58,  48,  39,  43,  59,  56,  49,  54,  64,  53,  61,  62,  68,
        52,  66,  51,  24,  34,  33,  23,  32,  38,  29,  37,  27,  42,
        72,  63,  69,  76,  67,  57,  28,  18,  19,  71,  78,  73,  74,
        83,  82,  98,  77,  88,  86,  14,   9,  97,  81,  79,  96,  84,
        89, 103, 101,  87,  92,  31,  26,  21,  13,  22,  17,  12,  16,
        11,   7,   8], dtype=int64)

In [24]:
data['Operating Profit'].unique()

array(['$300.000 ', '$150.000 ', '$140.000 ', ..., '$471 ', '$896 ',
       '$2.791 '], dtype=object)

In [25]:
data['Operating Profit'] = convert_series_from_dollar_to_number(data['Operating Profit'], 'int64')
data['Operating Profit'].unique()

array([300000, 150000, 140000, ...,    471,    896,   2791], dtype=int64)

In [26]:
data['Total Sales'].unique()

array(['$600.000 ', '$500.000 ', '$400.000 ', ..., '$4.902 ', '$5.664 ',
       '$8.784 '], dtype=object)

In [27]:
data['Total Sales'] = convert_series_from_dollar_to_number(data['Total Sales'], 'int64')
data['Total Sales'].unique()

array([600000, 500000, 400000, ...,   4902,   5664,   8784], dtype=int64)

In [28]:
data['Operating Margin'].unique()

array(['50%', '30%', '35%', '25%', '45%', '20%', '15%', '40%', '55%',
       '10%', '60%', '65%', '61%', '42%', '46%', '37%', '62%', '44%',
       '47%', '49%', '43%', '38%', '63%', '41%', '64%', '48%', '36%',
       '39%', '58%', '59%', '57%', '31%', '28%', '27%', '51%', '66%',
       '33%', '34%', '29%', '24%', '23%', '21%', '52%', '53%', '68%',
       '69%', '67%', '54%', '56%', '70%', '74%', '26%', '76%', '77%',
       '73%', '32%', '75%', '72%', '71%', '80%', '79%', '22%', '19%',
       '17%', '18%', '12%'], dtype=object)

In [29]:
data['Operating Margin']=data['Operating Margin'].map(lambda x: x[:-1]).astype('int64')


In [30]:
data['Operating Margin'].unique()

array([50, 30, 35, 25, 45, 20, 15, 40, 55, 10, 60, 65, 61, 42, 46, 37, 62,
       44, 47, 49, 43, 38, 63, 41, 64, 48, 36, 39, 58, 59, 57, 31, 28, 27,
       51, 66, 33, 34, 29, 24, 23, 21, 52, 53, 68, 69, 67, 54, 56, 70, 74,
       26, 76, 77, 73, 32, 75, 72, 71, 80, 79, 22, 19, 17, 18, 12],
      dtype=int64)

In [31]:
data['Units Sold'].unique()

array([1200, 1000,  850,  900, 1250,  950,  825, 1220,  925,  800,  875,
       1050, 1275, 1025, 1100, 1075, 1150,  975,  920,  700,  550,  675,
        625,  500,  600,  650,  725,  525,  775,  750,  575,  450,  425,
        475,  275,  125,  175,  225,  100,  495,  200,   75,  150,  250,
        350,  325,  400,  375,  300,  195,   50,  445,   25,  470, 1070,
       1125,  745,  145,  420,    0,   95,  545,  570,  320,  870,  820,
        520,  770,  795,  620,  295,  670,  345, 1020, 1045,  695,  945,
        595,  220,  720,  395,  645,  245,  270,  170,  336,  260,  247,
        234,  313,  261,  276,  206,  243,  290,  354,  259,  216,  230,
        238,  252,  239,  215,  317,  278,  305,  319,  267,  231,  286,
        308,  257,  241,  360,  268,  280,  236,  299,  273,  258,  254,
        263,  312,  285,  210,  154,  203,  213,  255,  176,  196,  182,
        174,  189,  163,  147,  232,  168,  169,  293,  297,  181,  240,
        188,  209,  194,  217,  161,  233,  223,  1

In [32]:
data['Sales Method'].unique()

array(['In-store', 'Outlet', 'Online'], dtype=object)

In [33]:
# Verification
data.dtypes

Retailer            object
Invoice Date        object
Region              object
State               object
City                object
Product             object
Price per Unit       int64
Units Sold           int64
Total Sales          int64
Operating Profit     int64
Operating Margin     int64
Sales Method        object
dtype: object

## Run the data.describe() function 

In [34]:
data.describe()

Price per Unit   Units Sold    Total Sales  Operating Profit  \
count     9648.000000  9648.000000    9648.000000       9648.000000   
mean        45.216625   256.930037   93273.437500      34425.282131   
std         14.705397   214.252030  141916.016727      54193.124141   
min          7.000000     0.000000       0.000000          0.000000   
25%         35.000000   106.000000    4254.500000       1922.000000   
50%         45.000000   176.000000    9576.000000       4371.500000   
75%         55.000000   350.000000  150000.000000      52063.000000   
max        110.000000  1275.000000  825000.000000     390000.000000   

       Operating Margin  
count       9648.000000  
mean          42.299129  
std            9.719742  
min           10.000000  
25%           35.000000  
50%           41.000000  
75%           49.000000  
max           80.000000

In [35]:
data.drop(data[(data['Units Sold'] == 0)].index, inplace=True)

In [36]:
data.describe()


Price per Unit   Units Sold    Total Sales  Operating Profit  \
count     9644.000000  9644.000000    9644.000000       9644.000000   
mean        45.222418   257.036603   93312.124119      34439.560556   
std         14.705565   214.232536  141932.729876      54199.826197   
min          7.000000     6.000000     160.000000         75.000000   
25%         35.000000   106.000000    4261.250000       1924.750000   
50%         45.000000   176.000000    9581.000000       4374.500000   
75%         55.000000   350.000000  150000.000000      52063.000000   
max        110.000000  1275.000000  825000.000000     390000.000000   

       Operating Margin  
count        9644.00000  
mean           42.29718  
std             9.72023  
min            10.00000  
25%            35.00000  
50%            41.00000  
75%            49.00000  
max            80.00000

In [37]:
data.to_csv(
    path.joinpath('02 data', 'Adidas_US_Sales-clean.csv'),
)